// Scripted Pipeline untuk React App - Windows

node {
    stage('Checkout') {
        checkout scm
    }

    stage('Install Dependencies') {
        // gunakan npm install karena tidak ada package-lock.json
        bat 'npm install'
    }

    stage('Build') {
        // Fix error: ERR_OSSL_EVP_UNSUPPORTED dengan openssl-legacy-provider
        bat 'set "NODE_OPTIONS=--openssl-legacy-provider" && npm run build'
    }

    stage('Test') {
        // Jika tidak ada test, tetap dianggap berhasil
        bat 'set "NODE_OPTIONS=--openssl-legacy-provider" && npm test -- --watch=false --passWithNoTests'
    }

    stage('Archive Build Artifacts') {
        archiveArtifacts artifacts: 'build/**/*', fingerprint: true
    }
}
